services:

  backend:
    build: .

    ports:
      - "2005:2005"

    depends_on:
      - mysql

    env_file:
      - .env.development

    environment:
      DB_HOST: mysql

  mysql:
    image: mysql:8

    restart: always

    env_file:
      - .env.development

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

    ports:
      - "3307:3306"